### ISSUE TITLE
Some patterns show up more than once

### ISSUE THREAD

**Issue by JackieNim** [iluwatar/java-design-patterns-web#18]
Some patterns show up more than once, an example of this is the adapter and singleton pattern

![image](https://user-images.githubusercontent.com/4138836/116289218-89239e80-a74f-11eb-91ab-909ce0cb9beb.png)

Not smart enough to fix it but looking in /pages/pattern line 11 site.pages probably has a duplicate. Not sure where this is being populated.

**Comment by JackieNim** [comment]
I have a potential fix, don't have permissions to push to a branch to make PR

**Comment by iluwatar** [comment]
Hi @JackieNim, thanks for notifying about the issue. Please use the normal Github's forking workflow i.e. fork the main repository to your own account and make the pull request from there. See https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by iluwatar** [comment]
By the way, there are other multiples also e.g. Singleton and Strategy. Not sure what's going on, maybe it's about localization...

**Comment by iluwatar** [comment]
@JackieNim detected another related problem, please see the description here https://github.com/iluwatar/java-design-patterns-web/issues/22
