### ISSUE TITLE
Some patterns displayed in wrong language

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns-web#22]
In issue https://github.com/iluwatar/java-design-patterns-web/issues/18 we fixed the patterns showing up more than once, but another problem came up. Some patterns now show in the wrong language e.g. Singleton displayed in Chinese. At the moment we support showing only English versions and the other ones can be filtered out.

**Comment by JackieNim** [comment]
Look into these PR's for the fix
This should go in first -> https://github.com/iluwatar/java-design-patterns/pull/1750
https://github.com/iluwatar/java-design-patterns-web/pull/24

**Comment by iluwatar** [comment]
@JackieNim the PR you mentioned seems to be closed 🤷🏻‍♂️

**Comment by JackieNim** [comment]
> @JackieNim the PR you mentioned seems to be closed 🤷🏻‍♂️

I created https://github.com/iluwatar/java-design-patterns/pull/1752 but seems like he doesnt want to review it again so 🤷

**Comment by iluwatar** [comment]
No worries @JackieNim, I think we can reopen it

**Comment by iluwatar** [comment]
Merged https://github.com/iluwatar/java-design-patterns/pull/1752

**Comment by iluwatar** [comment]
Merged https://github.com/iluwatar/java-design-patterns/pull/1752

**Comment by iluwatar** [comment]
Merged https://github.com/iluwatar/java-design-patterns-web/pull/24
