### ISSUE TITLE
Redesign front page

### ISSUE THREAD

**Issue by iluwatar** [iluwatar/java-design-patterns-web#9]
The current front page does not fulfill modern web site standards and should be redesigned. We are already using Bootstrap so something like this could be viable: https://getbootstrap.com/docs/4.4/examples/jumbotron/

Acceptance criteria
- Web site front page redesigned and taken to production

**Comment by hbothra15** [comment]
Hi @iluwatar ,
Are we just looking to get the first page ??

**Comment by iluwatar** [comment]
Yes, this is a face lift for the front page. Something like https://www.boardofinnovation.com/guides/ideation-guide/ should be doable with the current technologies.

**Comment by hbothra15** [comment]
I would like to try this out, can you point me to the page in repo and how to run the doc locally so that i can verify locally before making any change in repo

**Comment by hbothra15** [comment]
hi @iluwatar, I got the page which i might need to work on `java-design-patterns-web/_includes/header.html` but i would like to know more about your idea of the header, 
1. Are you looking for the spread out menu (alignment)
2. Do you have any logo which we can use.
3. Do you want to get rid of fontawesome icon ?

**Comment by iluwatar** [comment]
> I would like to try this out, can you point me to the page in repo and how to run the doc locally so that i can verify locally before making any change in repo

The instructions we currently have are available at https://github.com/iluwatar/java-design-patterns-web/wiki/1.-Quick-start

**Comment by iluwatar** [comment]
> Are you looking for the spread out menu (alignment)

I like the menu layout in https://www.boardofinnovation.com/guides/ideation-guide/. So there would be site logo in the top left corner and the menus would be aligned to the top right.

> Do you have any logo which we can use.

Unfortunately not yet, but if you have graphic design capability you're free to suggest any. Another option is to use some placeholder until we get the final logo.

> Do you want to get rid of fontawesome icon ?

I think we could remove those from the menu.

**Comment by hbothra15** [comment]
Hi @iluwatar ,
What's your take on the below logo
https://github.com/hbothra15/java-design-patterns-web/blob/master/static/img/logo.png

Thought behind this is we gives gear so that you can get the best brew
Although I guess we can avoid J.D.P text

**Comment by iluwatar** [comment]
Great idea @hbothra15 . I would style it a bit like this:
- remove the J.D.P. letters
- the gears look more like stars now, maybe shape them a little bit

**Comment by hbothra15** [comment]
> Great idea @hbothra15 . I would style it a bit like this:
> 
> * remove the J.D.P. letters
> * the gears look more like stars now, maybe shape them a little bit

Can you recheck at https://github.com/hbothra15/java-design-patterns-web/blob/redesignHeader/static/img/logo.png

**Comment by hbothra15** [comment]
Hi @iluwatar 
Can you checkout the new [logo](https://github.com/hbothra15/java-design-patterns-web/blob/redesignHeader/static/img/logoWithText.png) as well as I have update the Header with respect to new logo on branch https://github.com/hbothra15/java-design-patterns-web/tree/redesignHeader

**Comment by iluwatar** [comment]
@hbothra15 just had a chance to look at it. Looks great, I think! We can proceed with that header.

**Comment by iluwatar** [comment]
Implemented new front page
